# Generated by Django 3.0.3 on 2020-08-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, verbose_name='What is the name of the category?')),
                ('category_slug', models.SlugField(blank=True, default='abc')),
            ],
        ),
    ]
