# Generated by Django 3.0.3 on 2020-08-14 19:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20200814_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title of the Post')),
                ('body', models.TextField(verbose_name='Blog content')),
                ('picture_location', models.ImageField(max_length=200, upload_to='images/')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 8, 14, 19, 18, 51, 57636))),
                ('blog_slug', models.SlugField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
        ),
    ]
